### ISSUE TITLE
Integration to CMSSW master

### ISSUE THREAD

**Issue by makortel** [cerati/mkFit#236]
This issue is to track progress towards integrating mkFit to CMSSW master:

Overall (to get mkFit running within offline reco)
- [x] merge #235
- [x] maybe include #237 as well?
- [x] tag a new release
- [x] create mkFit external to [cmsdist](https://github.com/cms-sw/cmsdist), merged as https://github.com/cms-sw/cmsdist/pull/5150
   - [x] finalize mkFit external, merged as https://github.com/cms-sw/cmsdist/pull/5169
- [x] tag a new release following the merge of #241 
- [x] update mkFit external in cmsdist, merged as https://github.com/cms-sw/cmsdist/pull/5213
- [x] integrate `RecoTracker/MkFit` package from [makortel:mkfit_1040p1](https://github.com/makortel/cmssw/tree/mkfit_110x_integ) to CMSSW master, merged as https://github.com/cms-sw/cmssw/pull/27895
- [x] update mkFit with interface towards CMSSW to enable duplicate removal, done in #244
- [x] enable duplicate removal in `MkFitProducer`
- [x] Deal with non-x86 architectures #240
- [x] Deal with OpenMP runtime lib https://github.com/trackreco/mkFit/issues/257
- [x] Deal with SMatrix https://github.com/trackreco/mkFit/issues/258 (done in #264)
- [x] Fix backward fit for triplet seeds (#265)
- [ ] update mkFit external

Getting mkFit to run within HLT reconstruction some additional changes may be wanted
- [x] either re-open and merge https://github.com/cms-sw/cmssw/pull/26322, or remove or allow chancing the minimum hit cut for seeds in the seed cleaning, merged as https://github.com/cms-sw/cmssw/pull/28473 with a configuration flag https://github.com/trackreco/mkFit/blob/9afc251699bc3f07d4a02320ce229c25a8cffca9/Event.cc#L855
   * the seeds from quadruplet pixel tracks (as in HLT iter0 at the moment) get their last hit dropped, so the seed cleaning will drop all seeds in that case
   * of course all this will change for run3
- [x] make PR for https://github.com/makortel/cmssw/commit/ddd42d7c74ecabd9d4bf3b649bc40881ed76e8a0 (Add a flag to disable strip rechit matching), merged as https://github.com/cms-sw/cmssw/pull/28471
   * will become close-to-unnecessary once we get the GPU version of strip local reco
- [x] add customize function to use mkFit in HLT iter0 pattern recognition

**Comment by slava77** [comment]
>  either re-open and merge cms-sw/cmssw#26322, or remove or allow chancing the minimum hit cut for seeds in the seed cleaning 

I'm not sure that the CMSSW PR reopening will go so easily, because the original issue there is not addressed. Pattern reco turns out to deal with the outer hits better compared to the seeding. It didn't look like the POG was willing to commit to making things slightly worse under an assumption that it will all be done better anyways for the final Run 3 tracking.
Perhaps that regression goes away with the patatrack seeds with refit, but this will apparently not show up in CMSSW for some time.

In the current iterative tracking that we are using for tests all seeds are of the same length. So, this selection doesn't really make sense on a seed by seed level.
I propose to drop this cut.

**Comment by slava77** [comment]
> either re-open and merge [cms-sw/cmssw#26322](https://github.com/cms-sw/cmssw/pull/26322),

Oh, if you can percolate this addition as configurable, there should be no problem to get this PR in.

**Comment by makortel** [comment]
@slava77 tagged a new release https://github.com/trackreco/mkFit/releases/tag/V2.0.0-1+pr237

I have the full chain tested locally up to a runTheMatrix workflow running with a customize function changing the usual initialStep pattern recognition with mkFit.

**Comment by makortel** [comment]
The cmsdist PR is here https://github.com/cms-sw/cmsdist/pull/5150

**Comment by makortel** [comment]
Apparently cms-sw/cmsdist#5150 (merged on last Friday) was not sufficient to get the `mkfit` external usable from CMSSW, so I made a new PR to add the (hopefully last) missing piece https://github.com/cms-sw/cmsdist/pull/5169.

**Comment by slava77** [comment]
we should also add some "native" support to replace patches prepared in cms-sw/cmsdist#5174
@osschar you are probably the most familiar with the intrinsics to get it right.

**Comment by makortel** [comment]
> we should also add some "native" support to replace patches prepared in [cms-sw/cmsdist#5174](https://github.com/cms-sw/cmsdist/pull/5174)
> @osschar you are probably the most familiar with the intrinsics to get it right.

Let's follow up those in #240.

**Comment by osschar** [comment]
Well, it's not just what's the subject of #240 is (headers) ... we also need to:
1. massage the makefile, have some architecture detection in there
2. figure out how much time we want to spend on getting Matriplex intrinsic vectorization to work on arm and ppc (my guess is zero at this point) ... so the easiest would be to simply fall back to GenMul generating standard c++ and let the compilers try to vectorize that.
In any case, we need access to those machines with compilers cms uses to try things out.

**Comment by makortel** [comment]
The CMSSW PR is here https://github.com/cms-sw/cmssw/pull/27895

**Comment by makortel** [comment]
Just to document here that in light of the presentation at TRK POG on Monday showing the performance with #241, we just decided to cut a new release after its merge (now), and update the version in cmsdist.

**Comment by makortel** [comment]
> Just to document here that in light of the presentation at TRK POG on Monday showing the performance with #241, we just decided to cut a new release after its merge (now), and update the version in cmsdist.

We have a new release https://github.com/trackreco/mkFit/releases/tag/V2.0.1-0+pr241

**Comment by makortel** [comment]
> > Just to document here that in light of the presentation at TRK POG on Monday showing the performance with #241, we just decided to cut a new release after its merge (now), and update the version in cmsdist.
> 
> We have a new release https://github.com/trackreco/mkFit/releases/tag/V2.0.1-0+pr241

cmsdist PR is here https://github.com/cms-sw/cmsdist/pull/5213

**Comment by makortel** [comment]
#27895 was merged, the added matrix workflow 11634.7 is visible in IBs and running succesfully
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_0_X_2019-09-18-2300/pyRelValMatrixLogs/run/11634.7_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2021_GenSimFullINPUT+DigiFull_2021+RecoFull_trackingMkFit_2021+HARVESTFull_2021/step3_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2021_GenSimFullINPUT+DigiFull_2021+RecoFull_trackingMkFit_2021+HARVESTFull_2021.log#/

**Comment by makortel** [comment]
I'm leaving the issue open though until the HLT part is resolved as well.

**Comment by makortel** [comment]
This issue is effectively resolved
